<?php

namespace Database\Seeders;

use App\Models\Municipality;
use Illuminate\Database\Seeder;

class MunicipalitiesSeeder extends Seeder
{

    private $municipalitys;

    public function __construct()
    {
        /*
            set the default seeds array municipalitys and id departament
        */

        $this->municipalitys = [

            ['name' => 'Medellín', 'departament_Id' => 1],
            ['name' => 'Abejorral', 'departament_Id' => 1],
            ['name' => 'Abriaquí', 'departament_Id' => 1],
            ['name' => 'Alejandría', 'departament_Id' => 1],
            ['name' => 'Amagá', 'departament_Id' => 1],
            ['name' => 'Amalfi', 'departament_Id' => 1],
            ['name' => 'Andes', 'departament_Id' => 1],
            ['name' => 'Angelópolis', 'departament_Id' => 1],
            ['name' => 'Angostura', 'departament_Id' => 1],
            ['name' => 'Anorí', 'departament_Id' => 1],
            ['name' => 'Santa Fe De Antioquia', 'departament_Id' => 1],
            ['name' => 'Anzá', 'departament_Id' => 1],
            ['name' => 'Apartadó', 'departament_Id' => 1],
            ['name' => 'Arboletes', 'departament_Id' => 1],
            ['name' => 'Argelia', 'departament_Id' => 1],
            ['name' => 'Armenia', 'departament_Id' => 1],
            ['name' => 'Barbosa', 'departament_Id' => 1],
            ['name' => 'Belmira', 'departament_Id' => 1],
            ['name' => 'Bello', 'departament_Id' => 1],
            ['name' => 'Betania', 'departament_Id' => 1],
            ['name' => 'Betulia', 'departament_Id' => 1],
            ['name' => 'Ciudad Bolívar', 'departament_Id' => 1],
            ['name' => 'Briceño', 'departament_Id' => 1],
            ['name' => 'Buriticá', 'departament_Id' => 1],
            ['name' => 'Cáceres', 'departament_Id' => 1],
            ['name' => 'Caicedo', 'departament_Id' => 1],
            ['name' => 'Caldas', 'departament_Id' => 1],
            ['name' => 'Campamento', 'departament_Id' => 1],
            ['name' => 'Cañasgordas', 'departament_Id' => 1],
            ['name' => 'Caracolí', 'departament_Id' => 1],
            ['name' => 'Caramanta', 'departament_Id' => 1],
            ['name' => 'Carepa', 'departament_Id' => 1],
            ['name' => 'El Carmen De Viboral', 'departament_Id' => 1],
            ['name' => 'Carolina Del Príncipe', 'departament_Id' => 1],
            ['name' => 'Caucasia', 'departament_Id' => 1],
            ['name' => 'Chigorodó', 'departament_Id' => 1],
            ['name' => 'Cisneros', 'departament_Id' => 1],
            ['name' => 'Cocorná', 'departament_Id' => 1],
            ['name' => 'Concepción', 'departament_Id' => 1],
            ['name' => 'Concordia', 'departament_Id' => 1],
            ['name' => 'Copacabana', 'departament_Id' => 1],
            ['name' => 'Dabeiba', 'departament_Id' => 1],
            ['name' => 'Don Matias', 'departament_Id' => 1],
            ['name' => 'Ebéjico', 'departament_Id' => 1],
            ['name' => 'El Bagre', 'departament_Id' => 1],
            ['name' => 'Entrerríos', 'departament_Id' => 1],
            ['name' => 'Envigado', 'departament_Id' => 1],
            ['name' => 'Fredonia', 'departament_Id' => 1],
            ['name' => 'Frontino', 'departament_Id' => 1],
            ['name' => 'Giraldo', 'departament_Id' => 1],
            ['name' => 'Girardota', 'departament_Id' => 1],
            ['name' => 'Gómez Plata', 'departament_Id' => 1],
            ['name' => 'Granada', 'departament_Id' => 1],
            ['name' => 'Guadalupe', 'departament_Id' => 1],
            ['name' => 'Guarne', 'departament_Id' => 1],
            ['name' => 'Guatapé', 'departament_Id' => 1],
            ['name' => 'Heliconia', 'departament_Id' => 1],
            ['name' => 'Hispania', 'departament_Id' => 1],
            ['name' => 'Itagüí', 'departament_Id' => 1],
            ['name' => 'Ituango', 'departament_Id' => 1],
            ['name' => 'Jardín', 'departament_Id' => 1],
            ['name' => 'Jericó', 'departament_Id' => 1],
            ['name' => 'La Ceja', 'departament_Id' => 1],
            ['name' => 'La Estrella', 'departament_Id' => 1],
            ['name' => 'La Pintada', 'departament_Id' => 1],
            ['name' => 'La Unión', 'departament_Id' => 1],
            ['name' => 'Liborina', 'departament_Id' => 1],
            ['name' => 'Maceo', 'departament_Id' => 1],
            ['name' => 'Marinilla', 'departament_Id' => 1],
            ['name' => 'Montebello', 'departament_Id' => 1],
            ['name' => 'Murindó', 'departament_Id' => 1],
            ['name' => 'Mutatá', 'departament_Id' => 1],
            ['name' => 'Nariño', 'departament_Id' => 1],
            ['name' => 'Necoclí', 'departament_Id' => 1],
            ['name' => 'Nechí', 'departament_Id' => 1],
            ['name' => 'Olaya', 'departament_Id' => 1],
            ['name' => 'El Peñol', 'departament_Id' => 1],
            ['name' => 'Peque', 'departament_Id' => 1],
            ['name' => 'Pueblorrico', 'departament_Id' => 1],
            ['name' => 'Puerto Berrío', 'departament_Id' => 1],
            ['name' => 'Puerto Nare', 'departament_Id' => 1],
            ['name' => 'Puerto Triunfo', 'departament_Id' => 1],
            ['name' => 'Remedios', 'departament_Id' => 1],
            ['name' => 'El Retiro', 'departament_Id' => 1],
            ['name' => 'Rionegro', 'departament_Id' => 1],
            ['name' => 'Sabanalarga', 'departament_Id' => 1],
            ['name' => 'Sabaneta', 'departament_Id' => 1],
            ['name' => 'Salgar', 'departament_Id' => 1],
            ['name' => 'San Andrés', 'departament_Id' => 1],
            ['name' => 'San Carlos', 'departament_Id' => 1],
            ['name' => 'San Francisco', 'departament_Id' => 1],
            ['name' => 'San Jerónimo', 'departament_Id' => 1],
            ['name' => 'San José De La Montaña', 'departament_Id' => 1],
            ['name' => 'San Juan De Urabá', 'departament_Id' => 1],
            ['name' => 'San Luis', 'departament_Id' => 1],
            ['name' => 'San Pedro', 'departament_Id' => 1],
            ['name' => 'San Pedro De Urabá', 'departament_Id' => 1],
            ['name' => 'San Rafael', 'departament_Id' => 1],
            ['name' => 'San Roque', 'departament_Id' => 1],
            ['name' => 'San Vicente', 'departament_Id' => 1],
            ['name' => 'Santa Bárbara', 'departament_Id' => 1],
            ['name' => 'Santa Rosa De Osos', 'departament_Id' => 1],
            ['name' => 'Santo Domingo', 'departament_Id' => 1],
            ['name' => 'El Santuario', 'departament_Id' => 1],
            ['name' => 'Segovia', 'departament_Id' => 1],
            ['name' => 'Sonsón', 'departament_Id' => 1],
            ['name' => 'Sopetrán', 'departament_Id' => 1],
            ['name' => 'Támesis', 'departament_Id' => 1],
            ['name' => 'Tarazá', 'departament_Id' => 1],
            ['name' => 'Tarso', 'departament_Id' => 1],
            ['name' => 'Titiribí', 'departament_Id' => 1],
            ['name' => 'Toledo', 'departament_Id' => 1],
            ['name' => 'Turbo', 'departament_Id' => 1],
            ['name' => 'Uramita', 'departament_Id' => 1],
            ['name' => 'Urrao', 'departament_Id' => 1],
            ['name' => 'Valdivia', 'departament_Id' => 1],
            ['name' => 'Valparaíso', 'departament_Id' => 1],
            ['name' => 'Vegachí', 'departament_Id' => 1],
            ['name' => 'Venecia', 'departament_Id' => 1],
            ['name' => 'Vigía Del Fuerte', 'departament_Id' => 1],
            ['name' => 'Yalí', 'departament_Id' => 1],
            ['name' => 'Yarumal', 'departament_Id' => 1],
            ['name' => 'Yolombó', 'departament_Id' => 1],
            ['name' => 'Yondó', 'departament_Id' => 1],
            ['name' => 'Zaragoza', 'departament_Id' => 1],
            ['name' => 'Barranquilla', 'departament_Id' => 2],
            ['name' => 'Baranoa', 'departament_Id' => 2],
            ['name' => 'Campo De La Cruz', 'departament_Id' => 2],
            ['name' => 'Candelaria', 'departament_Id' => 2],
            ['name' => 'Galapa', 'departament_Id' => 2],
            ['name' => 'Juan De Acosta', 'departament_Id' => 2],
            ['name' => 'Luruaco', 'departament_Id' => 2],
            ['name' => 'Malambo', 'departament_Id' => 2],
            ['name' => 'Manatí', 'departament_Id' => 2],
            ['name' => 'Palmar De Varela', 'departament_Id' => 2],
            ['name' => 'Piojó', 'departament_Id' => 2],
            ['name' => 'Polonuevo', 'departament_Id' => 2],
            ['name' => 'Ponedera', 'departament_Id' => 2],
            ['name' => 'Puerto Colombia', 'departament_Id' => 2],
            ['name' => 'Repelón', 'departament_Id' => 2],
            ['name' => 'Sabanagrande', 'departament_Id' => 2],
            ['name' => 'Sabanalarga', 'departament_Id' => 2],
            ['name' => 'Santa Lucía', 'departament_Id' => 2],
            ['name' => 'Santo Tomás', 'departament_Id' => 2],
            ['name' => 'Soledad', 'departament_Id' => 2],
            ['name' => 'Suán', 'departament_Id' => 2],
            ['name' => 'Tubará', 'departament_Id' => 2],
            ['name' => 'Usiacurí', 'departament_Id' => 2],
            ['name' => 'Cartagena De Indias', 'departament_Id' => 3],
            ['name' => 'Achi', 'departament_Id' => 3],
            ['name' => 'Altos Del Rosario', 'departament_Id' => 3],
            ['name' => 'Arenal', 'departament_Id' => 3],
            ['name' => 'Arjona', 'departament_Id' => 3],
            ['name' => 'Arroyohondo', 'departament_Id' => 3],
            ['name' => 'Barranco De Loba', 'departament_Id' => 3],
            ['name' => 'Calamar', 'departament_Id' => 3],
            ['name' => 'Cantagallo', 'departament_Id' => 3],
            ['name' => 'Cicuco', 'departament_Id' => 3],
            ['name' => 'Córdoba', 'departament_Id' => 3],
            ['name' => 'Clemencia', 'departament_Id' => 3],
            ['name' => 'El Carmen De Bolívar', 'departament_Id' => 3],
            ['name' => 'El Guamo', 'departament_Id' => 3],
            ['name' => 'El Peñón', 'departament_Id' => 3],
            ['name' => 'Hatillo De Loba', 'departament_Id' => 3],
            ['name' => 'Magangué', 'departament_Id' => 3],
            ['name' => 'Mahates', 'departament_Id' => 3],
            ['name' => 'Margarita', 'departament_Id' => 3],
            ['name' => 'Maria La Baja', 'departament_Id' => 3],
            ['name' => 'Montecristo', 'departament_Id' => 3],
            ['name' => 'Mompos', 'departament_Id' => 3],
            ['name' => 'Norosí', 'departament_Id' => 3],
            ['name' => 'Morales', 'departament_Id' => 3],
            ['name' => 'Pinillos', 'departament_Id' => 3],
            ['name' => 'Regidor', 'departament_Id' => 3],
            ['name' => 'Rio Viejo', 'departament_Id' => 3],
            ['name' => 'San Cristóbal', 'departament_Id' => 3],
            ['name' => 'San Estanislao', 'departament_Id' => 3],
            ['name' => 'San Fernando', 'departament_Id' => 3],
            ['name' => 'San Jacinto', 'departament_Id' => 3],
            ['name' => 'San Jacinto Del Cauca', 'departament_Id' => 3],
            ['name' => 'San Juan Nepomuceno', 'departament_Id' => 3],
            ['name' => 'San Martín De Loba', 'departament_Id' => 3],
            ['name' => 'San Pablo', 'departament_Id' => 3],
            ['name' => 'Santa Catalina', 'departament_Id' => 3],
            ['name' => 'Santa Rosa', 'departament_Id' => 3],
            ['name' => 'Santa Rosa Del Sur', 'departament_Id' => 3],
            ['name' => 'Simiti', 'departament_Id' => 3],
            ['name' => 'Soplaviento', 'departament_Id' => 3],
            ['name' => 'Talaigua Nuevo', 'departament_Id' => 3],
            ['name' => 'Tiquisio', 'departament_Id' => 3],
            ['name' => 'Turbaco', 'departament_Id' => 3],
            ['name' => 'Turbaná', 'departament_Id' => 3],
            ['name' => 'Villanueva', 'departament_Id' => 3],
            ['name' => 'Zambrano', 'departament_Id' => 3],
            ['name' => 'Tunja', 'departament_Id' => 4],
            ['name' => 'Almeida', 'departament_Id' => 4],
            ['name' => 'Aquitania', 'departament_Id' => 4],
            ['name' => 'Arcabuco', 'departament_Id' => 4],
            ['name' => 'Belen', 'departament_Id' => 4],
            ['name' => 'Berbeo', 'departament_Id' => 4],
            ['name' => 'Beteitiva', 'departament_Id' => 4],
            ['name' => 'Boavita', 'departament_Id' => 4],
            ['name' => 'Boyacá', 'departament_Id' => 4],
            ['name' => 'Briceño', 'departament_Id' => 4],
            ['name' => 'Buenavista', 'departament_Id' => 4],
            ['name' => 'Busbanza', 'departament_Id' => 4],
            ['name' => 'Caldas', 'departament_Id' => 4],
            ['name' => 'Campohermoso', 'departament_Id' => 4],
            ['name' => 'Cerinza', 'departament_Id' => 4],
            ['name' => 'Chinavita', 'departament_Id' => 4],
            ['name' => 'Chiquinquirá', 'departament_Id' => 4],
            ['name' => 'Chiscas', 'departament_Id' => 4],
            ['name' => 'Chita', 'departament_Id' => 4],
            ['name' => 'Chitaraque', 'departament_Id' => 4],
            ['name' => 'Chivatá', 'departament_Id' => 4],
            ['name' => 'Ciénega', 'departament_Id' => 4],
            ['name' => 'Cómbita', 'departament_Id' => 4],
            ['name' => 'Coper', 'departament_Id' => 4],
            ['name' => 'Corrales', 'departament_Id' => 4],
            ['name' => 'Covarachia', 'departament_Id' => 4],
            ['name' => 'Cubará', 'departament_Id' => 4],
            ['name' => 'Cucaita', 'departament_Id' => 4],
            ['name' => 'Cuitiva', 'departament_Id' => 4],
            ['name' => 'Chiquiza', 'departament_Id' => 4],
            ['name' => 'Chivor', 'departament_Id' => 4],
            ['name' => 'Duitama', 'departament_Id' => 4],
            ['name' => 'El Cocuy', 'departament_Id' => 4],
            ['name' => 'El Espino', 'departament_Id' => 4],
            ['name' => 'Firavitoba', 'departament_Id' => 4],
            ['name' => 'Floresta', 'departament_Id' => 4],
            ['name' => 'Gachantiva', 'departament_Id' => 4],
            ['name' => 'Gámeza', 'departament_Id' => 4],
            ['name' => 'Garagoa', 'departament_Id' => 4],
            ['name' => 'Guacamayas', 'departament_Id' => 4],
            ['name' => 'Guateque', 'departament_Id' => 4],
            ['name' => 'Guayatá', 'departament_Id' => 4],
            ['name' => 'Güicán', 'departament_Id' => 4],
            ['name' => 'Iza', 'departament_Id' => 4],
            ['name' => 'Jenesano', 'departament_Id' => 4],
            ['name' => 'Jericó', 'departament_Id' => 4],
            ['name' => 'Labranzagrande', 'departament_Id' => 4],
            ['name' => 'La Capilla', 'departament_Id' => 4],
            ['name' => 'La Victoria', 'departament_Id' => 4],
            ['name' => 'La Uvita', 'departament_Id' => 4],
            ['name' => 'Villa De Leyva', 'departament_Id' => 4],
            ['name' => 'Macanal', 'departament_Id' => 4],
            ['name' => 'Maripi', 'departament_Id' => 4],
            ['name' => 'Miraflores', 'departament_Id' => 4],
            ['name' => 'Mongua', 'departament_Id' => 4],
            ['name' => 'Monguí', 'departament_Id' => 4],
            ['name' => 'Moniquirá', 'departament_Id' => 4],
            ['name' => 'Motavita', 'departament_Id' => 4],
            ['name' => 'Muzo', 'departament_Id' => 4],
            ['name' => 'Nobsa', 'departament_Id' => 4],
            ['name' => 'Nuevo Colón', 'departament_Id' => 4],
            ['name' => 'Oicatá', 'departament_Id' => 4],
            ['name' => 'Otanche', 'departament_Id' => 4],
            ['name' => 'Pachavita', 'departament_Id' => 4],
            ['name' => 'Páez', 'departament_Id' => 4],
            ['name' => 'Paipa', 'departament_Id' => 4],
            ['name' => 'Pajarito', 'departament_Id' => 4],
            ['name' => 'Panqueba', 'departament_Id' => 4],
            ['name' => 'Pauna', 'departament_Id' => 4],
            ['name' => 'Paya', 'departament_Id' => 4],
            ['name' => 'Paz Del Río', 'departament_Id' => 4],
            ['name' => 'Pesca', 'departament_Id' => 4],
            ['name' => 'Pisba', 'departament_Id' => 4],
            ['name' => 'Puerto Boyacá', 'departament_Id' => 4],
            ['name' => 'Quipama', 'departament_Id' => 4],
            ['name' => 'Ramiriquí', 'departament_Id' => 4],
            ['name' => 'Ráquira', 'departament_Id' => 4],
            ['name' => 'Rondón', 'departament_Id' => 4],
            ['name' => 'Saboyá', 'departament_Id' => 4],
            ['name' => 'Sáchica', 'departament_Id' => 4],
            ['name' => 'Samacá', 'departament_Id' => 4],
            ['name' => 'San Eduardo', 'departament_Id' => 4],
            ['name' => 'San José De Pare', 'departament_Id' => 4],
            ['name' => 'San Luis De Gaceno', 'departament_Id' => 4],
            ['name' => 'San Mateo', 'departament_Id' => 4],
            ['name' => 'San Miguel De Sema', 'departament_Id' => 4],
            ['name' => 'San Pablo Borbur', 'departament_Id' => 4],
            ['name' => 'Santana', 'departament_Id' => 4],
            ['name' => 'Santa María', 'departament_Id' => 4],
            ['name' => 'Santa Rosa De Viterbo', 'departament_Id' => 4],
            ['name' => 'Santa Sofía', 'departament_Id' => 4],
            ['name' => 'Sativanorte', 'departament_Id' => 4],
            ['name' => 'Sativasur', 'departament_Id' => 4],
            ['name' => 'Siachoque', 'departament_Id' => 4],
            ['name' => 'Soatá', 'departament_Id' => 4],
            ['name' => 'Socotá', 'departament_Id' => 4],
            ['name' => 'Socha', 'departament_Id' => 4],
            ['name' => 'Sogamoso', 'departament_Id' => 4],
            ['name' => 'Somondoco', 'departament_Id' => 4],
            ['name' => 'Sora', 'departament_Id' => 4],
            ['name' => 'Sotaquirá', 'departament_Id' => 4],
            ['name' => 'Soracá', 'departament_Id' => 4],
            ['name' => 'Susacón', 'departament_Id' => 4],
            ['name' => 'Sutamarchán', 'departament_Id' => 4],
            ['name' => 'Sutatenza', 'departament_Id' => 4],
            ['name' => 'Tasco', 'departament_Id' => 4],
            ['name' => 'Tenza', 'departament_Id' => 4],
            ['name' => 'Tibaná', 'departament_Id' => 4],
            ['name' => 'Tibasosa', 'departament_Id' => 4],
            ['name' => 'Tinjacá', 'departament_Id' => 4],
            ['name' => 'Tipacoque', 'departament_Id' => 4],
            ['name' => 'Toca', 'departament_Id' => 4],
            ['name' => 'Togüi', 'departament_Id' => 4],
            ['name' => 'Tópaga', 'departament_Id' => 4],
            ['name' => 'Tota', 'departament_Id' => 4],
            ['name' => 'Tununguá', 'departament_Id' => 4],
            ['name' => 'Turmequé', 'departament_Id' => 4],
            ['name' => 'Tuta', 'departament_Id' => 4],
            ['name' => 'Tutazá', 'departament_Id' => 4],
            ['name' => 'Úmbita', 'departament_Id' => 4],
            ['name' => 'Ventaquemada', 'departament_Id' => 4],
            ['name' => 'Viracachá', 'departament_Id' => 4],
            ['name' => 'Zetaquira', 'departament_Id' => 4],
            ['name' => 'Manizales', 'departament_Id' => 5],
            ['name' => 'Aguadas', 'departament_Id' => 5],
            ['name' => 'Anserma', 'departament_Id' => 5],
            ['name' => 'Aranzazu', 'departament_Id' => 5],
            ['name' => 'Belalcázar', 'departament_Id' => 5],
            ['name' => 'Chinchina', 'departament_Id' => 5],
            ['name' => 'Filadelfia', 'departament_Id' => 5],
            ['name' => 'La Dorada', 'departament_Id' => 5],
            ['name' => 'La Merced', 'departament_Id' => 5],
            ['name' => 'Manzanares', 'departament_Id' => 5],
            ['name' => 'Marmato', 'departament_Id' => 5],
            ['name' => 'Marquetalia', 'departament_Id' => 5],
            ['name' => 'Marulanda', 'departament_Id' => 5],
            ['name' => 'Neira', 'departament_Id' => 5],
            ['name' => 'Norcasia', 'departament_Id' => 5],
            ['name' => 'Pácora', 'departament_Id' => 5],
            ['name' => 'Palestina', 'departament_Id' => 5],
            ['name' => 'Pensilvania', 'departament_Id' => 5],
            ['name' => 'Riosucio', 'departament_Id' => 5],
            ['name' => 'Risaralda', 'departament_Id' => 5],
            ['name' => 'Salamina', 'departament_Id' => 5],
            ['name' => 'Samaná', 'departament_Id' => 5],
            ['name' => 'San José', 'departament_Id' => 5],
            ['name' => 'Supía', 'departament_Id' => 5],
            ['name' => 'Victoria', 'departament_Id' => 5],
            ['name' => 'Villamaria', 'departament_Id' => 5],
            ['name' => 'Viterbo', 'departament_Id' => 5],
            ['name' => 'Florencia', 'departament_Id' => 6],
            ['name' => 'Albania', 'departament_Id' => 6],
            ['name' => 'Belén De Los Andaquies', 'departament_Id' => 6],
            ['name' => 'Cartagena Del Chairá', 'departament_Id' => 6],
            ['name' => 'Currillo', 'departament_Id' => 6],
            ['name' => 'El Doncello', 'departament_Id' => 6],
            ['name' => 'El Paujil', 'departament_Id' => 6],
            ['name' => 'La Montañita', 'departament_Id' => 6],
            ['name' => 'Milán', 'departament_Id' => 6],
            ['name' => 'Morelia', 'departament_Id' => 6],
            ['name' => 'Puerto Rico', 'departament_Id' => 6],
            ['name' => 'San José Del Fragua', 'departament_Id' => 6],
            ['name' => 'San Vicente Del Caguán', 'departament_Id' => 6],
            ['name' => 'Solano', 'departament_Id' => 6],
            ['name' => 'Solita', 'departament_Id' => 6],
            ['name' => 'Valparaíso', 'departament_Id' => 6],
            ['name' => 'Popayán', 'departament_Id' => 7],
            ['name' => 'Almaguer', 'departament_Id' => 7],
            ['name' => 'Argelia', 'departament_Id' => 7],
            ['name' => 'Balboa', 'departament_Id' => 7],
            ['name' => 'Bolívar', 'departament_Id' => 7],
            ['name' => 'Buenos Aires', 'departament_Id' => 7],
            ['name' => 'Cajibío', 'departament_Id' => 7],
            ['name' => 'Caldono', 'departament_Id' => 7],
            ['name' => 'Caloto', 'departament_Id' => 7],
            ['name' => 'Corinto', 'departament_Id' => 7],
            ['name' => 'El Tambo', 'departament_Id' => 7],
            ['name' => 'Florencia', 'departament_Id' => 7],
            ['name' => 'Guachene', 'departament_Id' => 7],
            ['name' => 'Guapi', 'departament_Id' => 7],
            ['name' => 'Inzá', 'departament_Id' => 7],
            ['name' => 'Jambalo', 'departament_Id' => 7],
            ['name' => 'La Sierra', 'departament_Id' => 7],
            ['name' => 'La Vega', 'departament_Id' => 7],
            ['name' => 'Lopez', 'departament_Id' => 7],
            ['name' => 'Mercaderes', 'departament_Id' => 7],
            ['name' => 'Miranda', 'departament_Id' => 7],
            ['name' => 'Morales', 'departament_Id' => 7],
            ['name' => 'Padilla', 'departament_Id' => 7],
            ['name' => 'Páez', 'departament_Id' => 7],
            ['name' => 'Patía', 'departament_Id' => 7],
            ['name' => 'Piamonte', 'departament_Id' => 7],
            ['name' => 'Piendamó', 'departament_Id' => 7],
            ['name' => 'Puerto Tejada', 'departament_Id' => 7],
            ['name' => 'Puracé', 'departament_Id' => 7],
            ['name' => 'Rosas', 'departament_Id' => 7],
            ['name' => 'San Sebastian', 'departament_Id' => 7],
            ['name' => 'Santander De Quilichao', 'departament_Id' => 7],
            ['name' => 'Santa Rosa', 'departament_Id' => 7],
            ['name' => 'Silvia', 'departament_Id' => 7],
            ['name' => 'Sotara', 'departament_Id' => 7],
            ['name' => 'Suarez', 'departament_Id' => 7],
            ['name' => 'Sucre', 'departament_Id' => 7],
            ['name' => 'Timbío', 'departament_Id' => 7],
            ['name' => 'Timbiquí', 'departament_Id' => 7],
            ['name' => 'Toribio', 'departament_Id' => 7],
            ['name' => 'Totoró', 'departament_Id' => 7],
            ['name' => 'Villa Rica', 'departament_Id' => 7],
            ['name' => 'Valledupar', 'departament_Id' => 8],
            ['name' => 'Aguachica', 'departament_Id' => 8],
            ['name' => 'Agustín Codazzi', 'departament_Id' => 8],
            ['name' => 'Astrea', 'departament_Id' => 8],
            ['name' => 'Becerril', 'departament_Id' => 8],
            ['name' => 'Bosconia', 'departament_Id' => 8],
            ['name' => 'Chimichagua', 'departament_Id' => 8],
            ['name' => 'Chiriguana', 'departament_Id' => 8],
            ['name' => 'Curumaní', 'departament_Id' => 8],
            ['name' => 'El Copey', 'departament_Id' => 8],
            ['name' => 'El Paso', 'departament_Id' => 8],
            ['name' => 'Gamarra', 'departament_Id' => 8],
            ['name' => 'González', 'departament_Id' => 8],
            ['name' => 'La Gloria', 'departament_Id' => 8],
            ['name' => 'La Jagua De Ibirico', 'departament_Id' => 8],
            ['name' => 'Manaure', 'departament_Id' => 8],
            ['name' => 'Pailitas', 'departament_Id' => 8],
            ['name' => 'Pelaya', 'departament_Id' => 8],
            ['name' => 'Pueblo Bello', 'departament_Id' => 8],
            ['name' => 'Río De Oro', 'departament_Id' => 8],
            ['name' => 'La Paz', 'departament_Id' => 8],
            ['name' => 'San Alberto', 'departament_Id' => 8],
            ['name' => 'San Diego', 'departament_Id' => 8],
            ['name' => 'San Martín', 'departament_Id' => 8],
            ['name' => 'Tamalameque', 'departament_Id' => 8],
            ['name' => 'Montería', 'departament_Id' => 9],
            ['name' => 'Ayapel', 'departament_Id' => 9],
            ['name' => 'Buenavista', 'departament_Id' => 9],
            ['name' => 'Canalete', 'departament_Id' => 9],
            ['name' => 'Cereté', 'departament_Id' => 9],
            ['name' => 'Chima', 'departament_Id' => 9],
            ['name' => 'Chinú', 'departament_Id' => 9],
            ['name' => 'Ciénaga De Oro', 'departament_Id' => 9],
            ['name' => 'Cotorra', 'departament_Id' => 9],
            ['name' => 'La Apartada', 'departament_Id' => 9],
            ['name' => 'Lorica', 'departament_Id' => 9],
            ['name' => 'Los Córdobas', 'departament_Id' => 9],
            ['name' => 'Momil', 'departament_Id' => 9],
            ['name' => 'Montelíbano', 'departament_Id' => 9],
            ['name' => 'Moñitos', 'departament_Id' => 9],
            ['name' => 'Planeta Rica', 'departament_Id' => 9],
            ['name' => 'Pueblo Nuevo', 'departament_Id' => 9],
            ['name' => 'Puerto Escondido', 'departament_Id' => 9],
            ['name' => 'Puerto Libertador', 'departament_Id' => 9],
            ['name' => 'Purísima', 'departament_Id' => 9],
            ['name' => 'Sahagún', 'departament_Id' => 9],
            ['name' => 'San Andrés De Sotavento', 'departament_Id' => 9],
            ['name' => 'San Antero', 'departament_Id' => 9],
            ['name' => 'San Bernardo Del Viento', 'departament_Id' => 9],
            ['name' => 'San Carlos', 'departament_Id' => 9],
            ['name' => 'San Pelayo', 'departament_Id' => 9],
            ['name' => 'Tierralta', 'departament_Id' => 9],
            ['name' => 'Tuchín', 'departament_Id' => 9],
            ['name' => 'Valencia', 'departament_Id' => 9],
            ['name' => 'Agua De Dios', 'departament_Id' => 10],
            ['name' => 'Albán', 'departament_Id' => 10],
            ['name' => 'Anapoima', 'departament_Id' => 10],
            ['name' => 'Anolaima', 'departament_Id' => 10],
            ['name' => 'Arbeláez', 'departament_Id' => 10],
            ['name' => 'Beltrán', 'departament_Id' => 10],
            ['name' => 'Bituima', 'departament_Id' => 10],
            ['name' => 'Bogotá D.C.', 'departament_Id' => 10],
            ['name' => 'Bojacá', 'departament_Id' => 10],
            ['name' => 'Cabrera', 'departament_Id' => 10],
            ['name' => 'Cachipay', 'departament_Id' => 10],
            ['name' => 'Cajicá', 'departament_Id' => 10],
            ['name' => 'Caparrapí', 'departament_Id' => 10],
            ['name' => 'Caqueza', 'departament_Id' => 10],
            ['name' => 'Carmen De Carupa', 'departament_Id' => 10],
            ['name' => 'Chaguaní', 'departament_Id' => 10],
            ['name' => 'Chía', 'departament_Id' => 10],
            ['name' => 'Chipaque', 'departament_Id' => 10],
            ['name' => 'Choachí', 'departament_Id' => 10],
            ['name' => 'Chocontá', 'departament_Id' => 10],
            ['name' => 'Cogua', 'departament_Id' => 10],
            ['name' => 'Cota', 'departament_Id' => 10],
            ['name' => 'Cucunubá', 'departament_Id' => 10],
            ['name' => 'El Colegio', 'departament_Id' => 10],
            ['name' => 'El Peñón', 'departament_Id' => 10],
            ['name' => 'El Rosal', 'departament_Id' => 10],
            ['name' => 'Facatativá', 'departament_Id' => 10],
            ['name' => 'Fómeque', 'departament_Id' => 10],
            ['name' => 'Fosca', 'departament_Id' => 10],
            ['name' => 'Funza', 'departament_Id' => 10],
            ['name' => 'Fúquene', 'departament_Id' => 10],
            ['name' => 'Fusagasugá', 'departament_Id' => 10],
            ['name' => 'Gachalá', 'departament_Id' => 10],
            ['name' => 'Gachancipá', 'departament_Id' => 10],
            ['name' => 'Gachetá', 'departament_Id' => 10],
            ['name' => 'Gama', 'departament_Id' => 10],
            ['name' => 'Girardot', 'departament_Id' => 10],
            ['name' => 'Granada', 'departament_Id' => 10],
            ['name' => 'Guachetá', 'departament_Id' => 10],
            ['name' => 'Guaduas', 'departament_Id' => 10],
            ['name' => 'Guasca', 'departament_Id' => 10],
            ['name' => 'Guataquí', 'departament_Id' => 10],
            ['name' => 'Guatavita', 'departament_Id' => 10],
            ['name' => 'Guayabal De Siquima', 'departament_Id' => 10],
            ['name' => 'Guayabetal', 'departament_Id' => 10],
            ['name' => 'Gutiérrez', 'departament_Id' => 10],
            ['name' => 'Jerusalén', 'departament_Id' => 10],
            ['name' => 'Junín', 'departament_Id' => 10],
            ['name' => 'La Calera', 'departament_Id' => 10],
            ['name' => 'La Mesa', 'departament_Id' => 10],
            ['name' => 'La Palma', 'departament_Id' => 10],
            ['name' => 'La Peña', 'departament_Id' => 10],
            ['name' => 'La Vega', 'departament_Id' => 10],
            ['name' => 'Lenguazaque', 'departament_Id' => 10],
            ['name' => 'Macheta', 'departament_Id' => 10],
            ['name' => 'Madrid', 'departament_Id' => 10],
            ['name' => 'Manta', 'departament_Id' => 10],
            ['name' => 'Medina', 'departament_Id' => 10],
            ['name' => 'Mosquera', 'departament_Id' => 10],
            ['name' => 'Nariño', 'departament_Id' => 10],
            ['name' => 'Nemocón', 'departament_Id' => 10],
            ['name' => 'Nilo', 'departament_Id' => 10],
            ['name' => 'Nimaima', 'departament_Id' => 10],
            ['name' => 'Nocaima', 'departament_Id' => 10],
            ['name' => 'Venecia', 'departament_Id' => 10],
            ['name' => 'Pacho', 'departament_Id' => 10],
            ['name' => 'Paime', 'departament_Id' => 10],
            ['name' => 'Pandi', 'departament_Id' => 10],
            ['name' => 'Paratebueno', 'departament_Id' => 10],
            ['name' => 'Pasca', 'departament_Id' => 10],
            ['name' => 'Puerto Salgar', 'departament_Id' => 10],
            ['name' => 'Puli', 'departament_Id' => 10],
            ['name' => 'Quebradanegra', 'departament_Id' => 10],
            ['name' => 'Quetame', 'departament_Id' => 10],
            ['name' => 'Quipile', 'departament_Id' => 10],
            ['name' => 'Apulo', 'departament_Id' => 10],
            ['name' => 'Ricaurte', 'departament_Id' => 10],
            ['name' => 'San Antonio Del Tequendama', 'departament_Id' => 10],
            ['name' => 'San Bernardo', 'departament_Id' => 10],
            ['name' => 'San Cayetano', 'departament_Id' => 10],
            ['name' => 'San Francisco', 'departament_Id' => 10],
            ['name' => 'San Juan De Río Seco', 'departament_Id' => 10],
            ['name' => 'Sasaima', 'departament_Id' => 10],
            ['name' => 'Sesquilé', 'departament_Id' => 10],
            ['name' => 'Sibaté', 'departament_Id' => 10],
            ['name' => 'Silvania', 'departament_Id' => 10],
            ['name' => 'Simijaca', 'departament_Id' => 10],
            ['name' => 'Soacha', 'departament_Id' => 10],
            ['name' => 'Sopó', 'departament_Id' => 10],
            ['name' => 'Subachoque', 'departament_Id' => 10],
            ['name' => 'Suesca', 'departament_Id' => 10],
            ['name' => 'Supatá', 'departament_Id' => 10],
            ['name' => 'Susa', 'departament_Id' => 10],
            ['name' => 'Sutatausa', 'departament_Id' => 10],
            ['name' => 'Tabio', 'departament_Id' => 10],
            ['name' => 'Tausa', 'departament_Id' => 10],
            ['name' => 'Tena', 'departament_Id' => 10],
            ['name' => 'Tenjo', 'departament_Id' => 10],
            ['name' => 'Tibacuy', 'departament_Id' => 10],
            ['name' => 'Tibirita', 'departament_Id' => 10],
            ['name' => 'Tocaima', 'departament_Id' => 10],
            ['name' => 'Tocancipá', 'departament_Id' => 10],
            ['name' => 'Topaipí', 'departament_Id' => 10],
            ['name' => 'Ubalá', 'departament_Id' => 10],
            ['name' => 'Ubaque', 'departament_Id' => 10],
            ['name' => 'Ubaté', 'departament_Id' => 10],
            ['name' => 'Une', 'departament_Id' => 10],
            ['name' => 'Útica', 'departament_Id' => 10],
            ['name' => 'Vergara', 'departament_Id' => 10],
            ['name' => 'Viani', 'departament_Id' => 10],
            ['name' => 'Villagómez', 'departament_Id' => 10],
            ['name' => 'Villapinzón', 'departament_Id' => 10],
            ['name' => 'Villeta', 'departament_Id' => 10],
            ['name' => 'Viotá', 'departament_Id' => 10],
            ['name' => 'Yacopí', 'departament_Id' => 10],
            ['name' => 'Zipacón', 'departament_Id' => 10],
            ['name' => 'Zipaquirá', 'departament_Id' => 10],
            ['name' => 'Quibdó', 'departament_Id' => 11],
            ['name' => 'Acandí', 'departament_Id' => 11],
            ['name' => 'Alto Baudó', 'departament_Id' => 11],
            ['name' => 'El Atrato', 'departament_Id' => 11],
            ['name' => 'Bagadó', 'departament_Id' => 11],
            ['name' => 'Bahía Solano', 'departament_Id' => 11],
            ['name' => 'Bajo Baudó', 'departament_Id' => 11],
            ['name' => 'Bojayá', 'departament_Id' => 11],
            ['name' => 'Cantón De San Pablo', 'departament_Id' => 11],
            ['name' => 'El Carmén Del Darién', 'departament_Id' => 11],
            ['name' => 'Cértegui', 'departament_Id' => 11],
            ['name' => 'Condoto', 'departament_Id' => 11],
            ['name' => 'El Carmen De Atrato', 'departament_Id' => 11],
            ['name' => 'El Litoral Del San Juan', 'departament_Id' => 11],
            ['name' => 'Istmina', 'departament_Id' => 11],
            ['name' => 'Juradó', 'departament_Id' => 11],
            ['name' => 'Lloró', 'departament_Id' => 11],
            ['name' => 'Medio Atrato', 'departament_Id' => 11],
            ['name' => 'Medio Baudó', 'departament_Id' => 11],
            ['name' => 'Medio San Juan', 'departament_Id' => 11],
            ['name' => 'Nóvita', 'departament_Id' => 11],
            ['name' => 'Nuquí', 'departament_Id' => 11],
            ['name' => 'Rio Iró', 'departament_Id' => 11],
            ['name' => 'Rio Quito', 'departament_Id' => 11],
            ['name' => 'Riosucio', 'departament_Id' => 11],
            ['name' => 'San José Del Palmar', 'departament_Id' => 11],
            ['name' => 'Sipí', 'departament_Id' => 11],
            ['name' => 'Tadó', 'departament_Id' => 11],
            ['name' => 'Unguía', 'departament_Id' => 11],
            ['name' => 'Unión Panamericana', 'departament_Id' => 11],
            ['name' => 'Neiva', 'departament_Id' => 12],
            ['name' => 'Acevedo', 'departament_Id' => 12],
            ['name' => 'Agrado', 'departament_Id' => 12],
            ['name' => 'Aipe', 'departament_Id' => 12],
            ['name' => 'Algeciras', 'departament_Id' => 12],
            ['name' => 'Altamira', 'departament_Id' => 12],
            ['name' => 'Baraya', 'departament_Id' => 12],
            ['name' => 'Campoalegre', 'departament_Id' => 12],
            ['name' => 'Colombia', 'departament_Id' => 12],
            ['name' => 'Elías', 'departament_Id' => 12],
            ['name' => 'Garzón', 'departament_Id' => 12],
            ['name' => 'Gigante', 'departament_Id' => 12],
            ['name' => 'Guadalupe', 'departament_Id' => 12],
            ['name' => 'Hobo', 'departament_Id' => 12],
            ['name' => 'Íquira', 'departament_Id' => 12],
            ['name' => 'Isnos', 'departament_Id' => 12],
            ['name' => 'La Argentina', 'departament_Id' => 12],
            ['name' => 'La Plata', 'departament_Id' => 12],
            ['name' => 'Nátaga', 'departament_Id' => 12],
            ['name' => 'Oporapa', 'departament_Id' => 12],
            ['name' => 'Paicol', 'departament_Id' => 12],
            ['name' => 'Palermo', 'departament_Id' => 12],
            ['name' => 'Palestina', 'departament_Id' => 12],
            ['name' => 'Pital', 'departament_Id' => 12],
            ['name' => 'Pitalito', 'departament_Id' => 12],
            ['name' => 'Rivera', 'departament_Id' => 12],
            ['name' => 'Saladoblanco', 'departament_Id' => 12],
            ['name' => 'San Agustín', 'departament_Id' => 12],
            ['name' => 'Santa Maria', 'departament_Id' => 12],
            ['name' => 'Suaza', 'departament_Id' => 12],
            ['name' => 'Tarqui', 'departament_Id' => 12],
            ['name' => 'Tesalia', 'departament_Id' => 12],
            ['name' => 'Tello', 'departament_Id' => 12],
            ['name' => 'Teruel', 'departament_Id' => 12],
            ['name' => 'Timaná', 'departament_Id' => 12],
            ['name' => 'Villavieja', 'departament_Id' => 12],
            ['name' => 'Yaguará', 'departament_Id' => 12],
            ['name' => 'Riohacha', 'departament_Id' => 13],
            ['name' => 'Albania', 'departament_Id' => 13],
            ['name' => 'Barrancas', 'departament_Id' => 13],
            ['name' => 'Dibulla', 'departament_Id' => 13],
            ['name' => 'Distracción', 'departament_Id' => 13],
            ['name' => 'El Molino', 'departament_Id' => 13],
            ['name' => 'Fonseca', 'departament_Id' => 13],
            ['name' => 'Hatonuevo', 'departament_Id' => 13],
            ['name' => 'La Jagua Del Pilar', 'departament_Id' => 13],
            ['name' => 'Maicao', 'departament_Id' => 13],
            ['name' => 'Manaure', 'departament_Id' => 13],
            ['name' => 'San Juan Del Cesar', 'departament_Id' => 13],
            ['name' => 'Uribia', 'departament_Id' => 13],
            ['name' => 'Urumita', 'departament_Id' => 13],
            ['name' => 'Villanueva', 'departament_Id' => 13],
            ['name' => 'Santa Marta', 'departament_Id' => 14],
            ['name' => 'Algarrobo', 'departament_Id' => 14],
            ['name' => 'Aracataca', 'departament_Id' => 14],
            ['name' => 'Ariguani', 'departament_Id' => 14],
            ['name' => 'Cerro San Antonio', 'departament_Id' => 14],
            ['name' => 'Chibolo', 'departament_Id' => 14],
            ['name' => 'Ciénaga', 'departament_Id' => 14],
            ['name' => 'Concordia', 'departament_Id' => 14],
            ['name' => 'El Banco', 'departament_Id' => 14],
            ['name' => 'El Piñon', 'departament_Id' => 14],
            ['name' => 'El Reten', 'departament_Id' => 14],
            ['name' => 'Fundacion', 'departament_Id' => 14],
            ['name' => 'Guamal', 'departament_Id' => 14],
            ['name' => 'Nueva Granada', 'departament_Id' => 14],
            ['name' => 'Pedraza', 'departament_Id' => 14],
            ['name' => 'Pijiño Del Carmen', 'departament_Id' => 14],
            ['name' => 'Pivijay', 'departament_Id' => 14],
            ['name' => 'Plato', 'departament_Id' => 14],
            ['name' => 'Puebloviejo', 'departament_Id' => 14],
            ['name' => 'Remolino', 'departament_Id' => 14],
            ['name' => 'Sabanas De San Ángel', 'departament_Id' => 14],
            ['name' => 'Salamina', 'departament_Id' => 14],
            ['name' => 'San Sebastian De Buenavista', 'departament_Id' => 14],
            ['name' => 'San Zenón', 'departament_Id' => 14],
            ['name' => 'Santa Ana', 'departament_Id' => 14],
            ['name' => 'Santa Bárbara De Pinto', 'departament_Id' => 14],
            ['name' => 'Sitionuevo', 'departament_Id' => 14],
            ['name' => 'Tenerife', 'departament_Id' => 14],
            ['name' => 'Zapayán', 'departament_Id' => 14],
            ['name' => 'Zona Bananera', 'departament_Id' => 14],
            ['name' => 'Villavicencio', 'departament_Id' => 15],
            ['name' => 'Acacias', 'departament_Id' => 15],
            ['name' => 'Barranca De Upía', 'departament_Id' => 15],
            ['name' => 'Cabuyaro', 'departament_Id' => 15],
            ['name' => 'Castilla La Nueva', 'departament_Id' => 15],
            ['name' => 'Cubarral', 'departament_Id' => 15],
            ['name' => 'Cumaral', 'departament_Id' => 15],
            ['name' => 'El Calvario', 'departament_Id' => 15],
            ['name' => 'El Castillo', 'departament_Id' => 15],
            ['name' => 'El Dorado', 'departament_Id' => 15],
            ['name' => 'Fuente De Oro', 'departament_Id' => 15],
            ['name' => 'Granada', 'departament_Id' => 15],
            ['name' => 'Guamal', 'departament_Id' => 15],
            ['name' => 'Mapiripán', 'departament_Id' => 15],
            ['name' => 'Mesetas', 'departament_Id' => 15],
            ['name' => 'La Macarena', 'departament_Id' => 15],
            ['name' => 'Uribe', 'departament_Id' => 15],
            ['name' => 'Lejanías', 'departament_Id' => 15],
            ['name' => 'Puerto Concordia', 'departament_Id' => 15],
            ['name' => 'Puerto Gaitán', 'departament_Id' => 15],
            ['name' => 'Puerto López', 'departament_Id' => 15],
            ['name' => 'Puerto Lleras', 'departament_Id' => 15],
            ['name' => 'Puerto Rico', 'departament_Id' => 15],
            ['name' => 'Restrepo', 'departament_Id' => 15],
            ['name' => 'San Carlos Guaroa', 'departament_Id' => 15],
            ['name' => 'San Juan De Arama', 'departament_Id' => 15],
            ['name' => 'San Juanito', 'departament_Id' => 15],
            ['name' => 'San Martín', 'departament_Id' => 15],
            ['name' => 'Vistahermosa', 'departament_Id' => 15],
            ['name' => 'Pasto', 'departament_Id' => 16],
            ['name' => 'Alban', 'departament_Id' => 16],
            ['name' => 'Aldana', 'departament_Id' => 16],
            ['name' => 'Ancuya', 'departament_Id' => 16],
            ['name' => 'Arboleda', 'departament_Id' => 16],
            ['name' => 'Barbacoas', 'departament_Id' => 16],
            ['name' => 'Belen', 'departament_Id' => 16],
            ['name' => 'Buesaco', 'departament_Id' => 16],
            ['name' => 'Colón', 'departament_Id' => 16],
            ['name' => 'Consacá', 'departament_Id' => 16],
            ['name' => 'Contadero', 'departament_Id' => 16],
            ['name' => 'Córdoba', 'departament_Id' => 16],
            ['name' => 'Cuaspud', 'departament_Id' => 16],
            ['name' => 'Cumbal', 'departament_Id' => 16],
            ['name' => 'Cumbitara', 'departament_Id' => 16],
            ['name' => 'Chachagui', 'departament_Id' => 16],
            ['name' => 'El Charco', 'departament_Id' => 16],
            ['name' => 'El Peñol', 'departament_Id' => 16],
            ['name' => 'El Rosario', 'departament_Id' => 16],
            ['name' => 'El Tablon De Gomez', 'departament_Id' => 16],
            ['name' => 'El Tambo', 'departament_Id' => 16],
            ['name' => 'Funes', 'departament_Id' => 16],
            ['name' => 'Guachucal', 'departament_Id' => 16],
            ['name' => 'Guaitarilla', 'departament_Id' => 16],
            ['name' => 'Gualmatán', 'departament_Id' => 16],
            ['name' => 'Iles', 'departament_Id' => 16],
            ['name' => 'Imués', 'departament_Id' => 16],
            ['name' => 'Ipiales', 'departament_Id' => 16],
            ['name' => 'La Cruz', 'departament_Id' => 16],
            ['name' => 'La Florida', 'departament_Id' => 16],
            ['name' => 'La Llanada', 'departament_Id' => 16],
            ['name' => 'La Tola', 'departament_Id' => 16],
            ['name' => 'La Unión', 'departament_Id' => 16],
            ['name' => 'Leiva', 'departament_Id' => 16],
            ['name' => 'Linares', 'departament_Id' => 16],
            ['name' => 'Los Andes', 'departament_Id' => 16],
            ['name' => 'Magüí Payán', 'departament_Id' => 16],
            ['name' => 'Mallama', 'departament_Id' => 16],
            ['name' => 'Mosquera', 'departament_Id' => 16],
            ['name' => 'Nariño', 'departament_Id' => 16],
            ['name' => 'Olaya Herrera', 'departament_Id' => 16],
            ['name' => 'Ospina', 'departament_Id' => 16],
            ['name' => 'Francisco Pizarro', 'departament_Id' => 16],
            ['name' => 'Policarpa', 'departament_Id' => 16],
            ['name' => 'Potosí', 'departament_Id' => 16],
            ['name' => 'Providencia', 'departament_Id' => 16],
            ['name' => 'Puerres', 'departament_Id' => 16],
            ['name' => 'Pupiales', 'departament_Id' => 16],
            ['name' => 'Ricaurte', 'departament_Id' => 16],
            ['name' => 'Roberto Payán', 'departament_Id' => 16],
            ['name' => 'Samaniego', 'departament_Id' => 16],
            ['name' => 'Sandoná', 'departament_Id' => 16],
            ['name' => 'San Bernardo', 'departament_Id' => 16],
            ['name' => 'San Lorenzo', 'departament_Id' => 16],
            ['name' => 'San Pablo', 'departament_Id' => 16],
            ['name' => 'San Pedro De Cartago', 'departament_Id' => 16],
            ['name' => 'Santa Barbara', 'departament_Id' => 16],
            ['name' => 'Santacruz', 'departament_Id' => 16],
            ['name' => 'Sapuyes', 'departament_Id' => 16],
            ['name' => 'Taminango', 'departament_Id' => 16],
            ['name' => 'Tangua', 'departament_Id' => 16],
            ['name' => 'San Andres De Tumaco', 'departament_Id' => 16],
            ['name' => 'Túquerres', 'departament_Id' => 16],
            ['name' => 'Yacuanquer', 'departament_Id' => 16],
            ['name' => 'Cúcuta', 'departament_Id' => 17],
            ['name' => 'Abrego', 'departament_Id' => 17],
            ['name' => 'Arboledas', 'departament_Id' => 17],
            ['name' => 'Bochalema', 'departament_Id' => 17],
            ['name' => 'Bucarasica', 'departament_Id' => 17],
            ['name' => 'Cácota', 'departament_Id' => 17],
            ['name' => 'Cachirá', 'departament_Id' => 17],
            ['name' => 'Chinácota', 'departament_Id' => 17],
            ['name' => 'Chitaga', 'departament_Id' => 17],
            ['name' => 'Convencion', 'departament_Id' => 17],
            ['name' => 'Cucutilla', 'departament_Id' => 17],
            ['name' => 'Duranía', 'departament_Id' => 17],
            ['name' => 'El Carmen', 'departament_Id' => 17],
            ['name' => 'El Tarra', 'departament_Id' => 17],
            ['name' => 'El Zulia', 'departament_Id' => 17],
            ['name' => 'Gramalote', 'departament_Id' => 17],
            ['name' => 'Hacarí', 'departament_Id' => 17],
            ['name' => 'Herrán', 'departament_Id' => 17],
            ['name' => 'Labateca', 'departament_Id' => 17],
            ['name' => 'La Esperanza', 'departament_Id' => 17],
            ['name' => 'La Playa', 'departament_Id' => 17],
            ['name' => 'Los Patios', 'departament_Id' => 17],
            ['name' => 'Lourdes', 'departament_Id' => 17],
            ['name' => 'Mutiscua', 'departament_Id' => 17],
            ['name' => 'Ocaña', 'departament_Id' => 17],
            ['name' => 'Pamplona', 'departament_Id' => 17],
            ['name' => 'Pamplonita', 'departament_Id' => 17],
            ['name' => 'Puerto Santander', 'departament_Id' => 17],
            ['name' => 'Ragonvalia', 'departament_Id' => 17],
            ['name' => 'Salazar', 'departament_Id' => 17],
            ['name' => 'San Calixto', 'departament_Id' => 17],
            ['name' => 'San Cayetano', 'departament_Id' => 17],
            ['name' => 'Santiago', 'departament_Id' => 17],
            ['name' => 'Sardinata', 'departament_Id' => 17],
            ['name' => 'Silos', 'departament_Id' => 17],
            ['name' => 'Teorama', 'departament_Id' => 17],
            ['name' => 'Tibú', 'departament_Id' => 17],
            ['name' => 'Toledo', 'departament_Id' => 17],
            ['name' => 'Villa Caro', 'departament_Id' => 17],
            ['name' => 'Villa Del Rosario', 'departament_Id' => 17],
            ['name' => 'Armenia', 'departament_Id' => 18],
            ['name' => 'Buenavista', 'departament_Id' => 18],
            ['name' => 'Calarcá', 'departament_Id' => 18],
            ['name' => 'Circasia', 'departament_Id' => 18],
            ['name' => 'Córdoba', 'departament_Id' => 18],
            ['name' => 'Filandia', 'departament_Id' => 18],
            ['name' => 'Génova', 'departament_Id' => 18],
            ['name' => 'La Tebaida', 'departament_Id' => 18],
            ['name' => 'Montenegro', 'departament_Id' => 18],
            ['name' => 'Pijao', 'departament_Id' => 18],
            ['name' => 'Quimbaya', 'departament_Id' => 18],
            ['name' => 'Salento', 'departament_Id' => 18],
            ['name' => 'Pereira', 'departament_Id' => 19],
            ['name' => 'Apía', 'departament_Id' => 19],
            ['name' => 'Balboa', 'departament_Id' => 19],
            ['name' => 'Belén De Umbría', 'departament_Id' => 19],
            ['name' => 'Dosquebradas', 'departament_Id' => 19],
            ['name' => 'Guática', 'departament_Id' => 19],
            ['name' => 'La Celia', 'departament_Id' => 19],
            ['name' => 'La Virginia', 'departament_Id' => 19],
            ['name' => 'Marsella', 'departament_Id' => 19],
            ['name' => 'Mistrató', 'departament_Id' => 19],
            ['name' => 'Pueblo Rico', 'departament_Id' => 19],
            ['name' => 'Quinchía', 'departament_Id' => 19],
            ['name' => 'Santa Rosa De Cabal', 'departament_Id' => 19],
            ['name' => 'Santuario', 'departament_Id' => 19],
            ['name' => 'Bucaramanga', 'departament_Id' => 20],
            ['name' => 'Aguada', 'departament_Id' => 20],
            ['name' => 'Albania', 'departament_Id' => 20],
            ['name' => 'Aratoca', 'departament_Id' => 20],
            ['name' => 'Barbosa', 'departament_Id' => 20],
            ['name' => 'Barichara', 'departament_Id' => 20],
            ['name' => 'Barrancabermeja', 'departament_Id' => 20],
            ['name' => 'Betulia', 'departament_Id' => 20],
            ['name' => 'Bolívar', 'departament_Id' => 20],
            ['name' => 'Cabrera', 'departament_Id' => 20],
            ['name' => 'California', 'departament_Id' => 20],
            ['name' => 'Capitanejo', 'departament_Id' => 20],
            ['name' => 'Carcasi', 'departament_Id' => 20],
            ['name' => 'Cepitá', 'departament_Id' => 20],
            ['name' => 'Cerrito', 'departament_Id' => 20],
            ['name' => 'Charalá', 'departament_Id' => 20],
            ['name' => 'Charta', 'departament_Id' => 20],
            ['name' => 'Chima', 'departament_Id' => 20],
            ['name' => 'Chipatá', 'departament_Id' => 20],
            ['name' => 'Cimitarra', 'departament_Id' => 20],
            ['name' => 'Concepción', 'departament_Id' => 20],
            ['name' => 'Confines', 'departament_Id' => 20],
            ['name' => 'Contratación', 'departament_Id' => 20],
            ['name' => 'Coromoro', 'departament_Id' => 20],
            ['name' => 'Curití', 'departament_Id' => 20],
            ['name' => 'El Carmen De Chucurí', 'departament_Id' => 20],
            ['name' => 'El Guacamayo', 'departament_Id' => 20],
            ['name' => 'El Peñón', 'departament_Id' => 20],
            ['name' => 'El Playón', 'departament_Id' => 20],
            ['name' => 'Encino', 'departament_Id' => 20],
            ['name' => 'Enciso', 'departament_Id' => 20],
            ['name' => 'Florián', 'departament_Id' => 20],
            ['name' => 'Floridablanca', 'departament_Id' => 20],
            ['name' => 'Galán', 'departament_Id' => 20],
            ['name' => 'Gámbita', 'departament_Id' => 20],
            ['name' => 'Girón', 'departament_Id' => 20],
            ['name' => 'Guaca', 'departament_Id' => 20],
            ['name' => 'Guadalupe', 'departament_Id' => 20],
            ['name' => 'Guapotá', 'departament_Id' => 20],
            ['name' => 'Guavatá', 'departament_Id' => 20],
            ['name' => 'Güepsa', 'departament_Id' => 20],
            ['name' => 'Hato', 'departament_Id' => 20],
            ['name' => 'Jesús Maria', 'departament_Id' => 20],
            ['name' => 'Jordán', 'departament_Id' => 20],
            ['name' => 'La Belleza', 'departament_Id' => 20],
            ['name' => 'Landázuri', 'departament_Id' => 20],
            ['name' => 'La Paz', 'departament_Id' => 20],
            ['name' => 'Lebríja', 'departament_Id' => 20],
            ['name' => 'Los Santos', 'departament_Id' => 20],
            ['name' => 'Macaravita', 'departament_Id' => 20],
            ['name' => 'Málaga', 'departament_Id' => 20],
            ['name' => 'Matanza', 'departament_Id' => 20],
            ['name' => 'Mogotes', 'departament_Id' => 20],
            ['name' => 'Molagavita', 'departament_Id' => 20],
            ['name' => 'Ocamonte', 'departament_Id' => 20],
            ['name' => 'Oiba', 'departament_Id' => 20],
            ['name' => 'Onzaga', 'departament_Id' => 20],
            ['name' => 'Palmar', 'departament_Id' => 20],
            ['name' => 'Palmas Del Socorro', 'departament_Id' => 20],
            ['name' => 'Páramo', 'departament_Id' => 20],
            ['name' => 'Piedecuesta', 'departament_Id' => 20],
            ['name' => 'Pinchote', 'departament_Id' => 20],
            ['name' => 'Puente Nacional', 'departament_Id' => 20],
            ['name' => 'Puerto Parra', 'departament_Id' => 20],
            ['name' => 'Puerto Wilches', 'departament_Id' => 20],
            ['name' => 'Rionegro', 'departament_Id' => 20],
            ['name' => 'Sabana De Torres', 'departament_Id' => 20],
            ['name' => 'San Andrés', 'departament_Id' => 20],
            ['name' => 'San Benito', 'departament_Id' => 20],
            ['name' => 'San Gil', 'departament_Id' => 20],
            ['name' => 'San Joaquín', 'departament_Id' => 20],
            ['name' => 'San José De Miranda', 'departament_Id' => 20],
            ['name' => 'San Miguel', 'departament_Id' => 20],
            ['name' => 'San Vicente De Chucurí', 'departament_Id' => 20],
            ['name' => 'Santa Barbara', 'departament_Id' => 20],
            ['name' => 'Santa Helena Del Opón', 'departament_Id' => 20],
            ['name' => 'Simacota', 'departament_Id' => 20],
            ['name' => 'Socorro', 'departament_Id' => 20],
            ['name' => 'Suaita', 'departament_Id' => 20],
            ['name' => 'Sucre', 'departament_Id' => 20],
            ['name' => 'Suratá', 'departament_Id' => 20],
            ['name' => 'Tona', 'departament_Id' => 20],
            ['name' => 'Valle De San José', 'departament_Id' => 20],
            ['name' => 'Vélez', 'departament_Id' => 20],
            ['name' => 'Vetas', 'departament_Id' => 20],
            ['name' => 'Villanueva', 'departament_Id' => 20],
            ['name' => 'Zapatoca', 'departament_Id' => 20],
            ['name' => 'Sincelejo', 'departament_Id' => 21],
            ['name' => 'Buenavista', 'departament_Id' => 21],
            ['name' => 'Caimito', 'departament_Id' => 21],
            ['name' => 'Colosó', 'departament_Id' => 21],
            ['name' => 'Corozal', 'departament_Id' => 21],
            ['name' => 'Coveñas', 'departament_Id' => 21],
            ['name' => 'Chalán', 'departament_Id' => 21],
            ['name' => 'El Roble', 'departament_Id' => 21],
            ['name' => 'Galeras', 'departament_Id' => 21],
            ['name' => 'Guaranda', 'departament_Id' => 21],
            ['name' => 'La Unión', 'departament_Id' => 21],
            ['name' => 'Los Palmitos', 'departament_Id' => 21],
            ['name' => 'Majagual', 'departament_Id' => 21],
            ['name' => 'Morroa', 'departament_Id' => 21],
            ['name' => 'Ovejas', 'departament_Id' => 21],
            ['name' => 'Palmito', 'departament_Id' => 21],
            ['name' => 'Sampués', 'departament_Id' => 21],
            ['name' => 'San Benito Abad', 'departament_Id' => 21],
            ['name' => 'San Juan Betulia', 'departament_Id' => 21],
            ['name' => 'San Marcos', 'departament_Id' => 21],
            ['name' => 'San Onofre', 'departament_Id' => 21],
            ['name' => 'San Pedro', 'departament_Id' => 21],
            ['name' => 'San Luis De Sincé', 'departament_Id' => 21],
            ['name' => 'Sucre', 'departament_Id' => 21],
            ['name' => 'Santiago De Tolú', 'departament_Id' => 21],
            ['name' => 'Tolú Viejo', 'departament_Id' => 21],
            ['name' => 'Ibagué', 'departament_Id' => 22],
            ['name' => 'Alpujarra', 'departament_Id' => 22],
            ['name' => 'Alvarado', 'departament_Id' => 22],
            ['name' => 'Ambalema', 'departament_Id' => 22],
            ['name' => 'Anzoátegui', 'departament_Id' => 22],
            ['name' => 'Armero', 'departament_Id' => 22],
            ['name' => 'Ataco', 'departament_Id' => 22],
            ['name' => 'Cajamarca', 'departament_Id' => 22],
            ['name' => 'Carmen De Apicalá', 'departament_Id' => 22],
            ['name' => 'Casabianca', 'departament_Id' => 22],
            ['name' => 'Chaparral', 'departament_Id' => 22],
            ['name' => 'Coello', 'departament_Id' => 22],
            ['name' => 'Coyaima', 'departament_Id' => 22],
            ['name' => 'Cunday', 'departament_Id' => 22],
            ['name' => 'Dolores', 'departament_Id' => 22],
            ['name' => 'Espinal', 'departament_Id' => 22],
            ['name' => 'Falan', 'departament_Id' => 22],
            ['name' => 'Flandes', 'departament_Id' => 22],
            ['name' => 'Fresno', 'departament_Id' => 22],
            ['name' => 'Guamo', 'departament_Id' => 22],
            ['name' => 'Herveo', 'departament_Id' => 22],
            ['name' => 'Honda', 'departament_Id' => 22],
            ['name' => 'Icononzo', 'departament_Id' => 22],
            ['name' => 'Lérida', 'departament_Id' => 22],
            ['name' => 'Líbano', 'departament_Id' => 22],
            ['name' => 'Mariquita', 'departament_Id' => 22],
            ['name' => 'Melgar', 'departament_Id' => 22],
            ['name' => 'Murillo', 'departament_Id' => 22],
            ['name' => 'Natagaima', 'departament_Id' => 22],
            ['name' => 'Ortega', 'departament_Id' => 22],
            ['name' => 'Palocabildo', 'departament_Id' => 22],
            ['name' => 'Piedras', 'departament_Id' => 22],
            ['name' => 'Planadas', 'departament_Id' => 22],
            ['name' => 'Prado', 'departament_Id' => 22],
            ['name' => 'Purificación', 'departament_Id' => 22],
            ['name' => 'Rioblanco', 'departament_Id' => 22],
            ['name' => 'Roncesvalles', 'departament_Id' => 22],
            ['name' => 'Rovira', 'departament_Id' => 22],
            ['name' => 'Saldaña', 'departament_Id' => 22],
            ['name' => 'San Antonio', 'departament_Id' => 22],
            ['name' => 'San Luis', 'departament_Id' => 22],
            ['name' => 'Santa Isabel', 'departament_Id' => 22],
            ['name' => 'Suarez', 'departament_Id' => 22],
            ['name' => 'Valle De San Juan', 'departament_Id' => 22],
            ['name' => 'Venadillo', 'departament_Id' => 22],
            ['name' => 'Villahermosa', 'departament_Id' => 22],
            ['name' => 'Villarrica', 'departament_Id' => 22],
            ['name' => 'Cali', 'departament_Id' => 23],
            ['name' => 'Alcala', 'departament_Id' => 23],
            ['name' => 'Andalucía', 'departament_Id' => 23],
            ['name' => 'Ansermanuevo', 'departament_Id' => 23],
            ['name' => 'Argelia', 'departament_Id' => 23],
            ['name' => 'Bolívar', 'departament_Id' => 23],
            ['name' => 'Buenaventura', 'departament_Id' => 23],
            ['name' => 'Guadalajara De Buga', 'departament_Id' => 23],
            ['name' => 'Bugalagrande', 'departament_Id' => 23],
            ['name' => 'Caicedonia', 'departament_Id' => 23],
            ['name' => 'Calima', 'departament_Id' => 23],
            ['name' => 'Candelaria', 'departament_Id' => 23],
            ['name' => 'Cartago', 'departament_Id' => 23],
            ['name' => 'Dagua', 'departament_Id' => 23],
            ['name' => 'El Águila', 'departament_Id' => 23],
            ['name' => 'El Cairo', 'departament_Id' => 23],
            ['name' => 'El Cerrito', 'departament_Id' => 23],
            ['name' => 'El Dovio', 'departament_Id' => 23],
            ['name' => 'Florida', 'departament_Id' => 23],
            ['name' => 'Ginebra', 'departament_Id' => 23],
            ['name' => 'Guacarí', 'departament_Id' => 23],
            ['name' => 'Jamundí', 'departament_Id' => 23],
            ['name' => 'La Cumbre', 'departament_Id' => 23],
            ['name' => 'La Unión', 'departament_Id' => 23],
            ['name' => 'La Victoria', 'departament_Id' => 23],
            ['name' => 'Obando', 'departament_Id' => 23],
            ['name' => 'Palmira', 'departament_Id' => 23],
            ['name' => 'Pradera', 'departament_Id' => 23],
            ['name' => 'Restrepo', 'departament_Id' => 23],
            ['name' => 'Riofrio', 'departament_Id' => 23],
            ['name' => 'Roldanillo', 'departament_Id' => 23],
            ['name' => 'San Pedro', 'departament_Id' => 23],
            ['name' => 'Sevilla', 'departament_Id' => 23],
            ['name' => 'Toro', 'departament_Id' => 23],
            ['name' => 'Trujillo', 'departament_Id' => 23],
            ['name' => 'Tuluá', 'departament_Id' => 23],
            ['name' => 'Ulloa', 'departament_Id' => 23],
            ['name' => 'Versalles', 'departament_Id' => 23],
            ['name' => 'Vijes', 'departament_Id' => 23],
            ['name' => 'Yotoco', 'departament_Id' => 23],
            ['name' => 'Yumbo', 'departament_Id' => 23],
            ['name' => 'Zarzal', 'departament_Id' => 23],
            ['name' => 'Yopal', 'departament_Id' => 25],
            ['name' => 'Arauca', 'departament_Id' => 24],
            ['name' => 'Arauquita', 'departament_Id' => 24],
            ['name' => 'Cravo Norte', 'departament_Id' => 24],
            ['name' => 'Fortul', 'departament_Id' => 24],
            ['name' => 'Puerto Rondón', 'departament_Id' => 24],
            ['name' => 'Saravena', 'departament_Id' => 24],
            ['name' => 'Tame', 'departament_Id' => 24],
            ['name' => 'Aguazul', 'departament_Id' => 25],
            ['name' => 'Chámeza', 'departament_Id' => 25],
            ['name' => 'Hato Corozal', 'departament_Id' => 25],
            ['name' => 'La Salina', 'departament_Id' => 25],
            ['name' => 'Maní', 'departament_Id' => 25],
            ['name' => 'Monterrey', 'departament_Id' => 25],
            ['name' => 'Nunchía', 'departament_Id' => 25],
            ['name' => 'Orocué', 'departament_Id' => 25],
            ['name' => 'Paz De Ariporo', 'departament_Id' => 25],
            ['name' => 'Pore', 'departament_Id' => 25],
            ['name' => 'Recetor', 'departament_Id' => 25],
            ['name' => 'Sabanalarga', 'departament_Id' => 25],
            ['name' => 'Sácama', 'departament_Id' => 25],
            ['name' => 'San Luis De Palenque', 'departament_Id' => 25],
            ['name' => 'Támara', 'departament_Id' => 25],
            ['name' => 'Tauramena', 'departament_Id' => 25],
            ['name' => 'Trinidad', 'departament_Id' => 25],
            ['name' => 'Villanueva', 'departament_Id' => 25],
            ['name' => 'Mocoa', 'departament_Id' => 26],
            ['name' => 'Colon', 'departament_Id' => 26],
            ['name' => 'Orito', 'departament_Id' => 26],
            ['name' => 'Puerto Asis', 'departament_Id' => 26],
            ['name' => 'Puerto Caicedo', 'departament_Id' => 26],
            ['name' => 'Puerto Guzmán', 'departament_Id' => 26],
            ['name' => 'Puerto Leguizamo', 'departament_Id' => 26],
            ['name' => 'Sibundoy', 'departament_Id' => 26],
            ['name' => 'San Francisco', 'departament_Id' => 26],
            ['name' => 'San Miguel', 'departament_Id' => 26],
            ['name' => 'Santiago', 'departament_Id' => 26],
            ['name' => 'Valle Del Guamuez', 'departament_Id' => 26],
            ['name' => 'Villagarzón', 'departament_Id' => 26],
            ['name' => 'San Andrés', 'departament_Id' => 27],
            ['name' => 'Providencia Y Santa Catalina', 'departament_Id' => 27],
            ['name' => 'Leticia', 'departament_Id' => 28],
            ['name' => 'El Encanto', 'departament_Id' => 28],
            ['name' => 'La Chorrera', 'departament_Id' => 28],
            ['name' => 'La Pedrera', 'departament_Id' => 28],
            ['name' => 'La Victoria', 'departament_Id' => 28],
            ['name' => 'Miriti - Paraná', 'departament_Id' => 28],
            ['name' => 'Puerto Alegría', 'departament_Id' => 28],
            ['name' => 'Puerto Arica', 'departament_Id' => 28],
            ['name' => 'Puerto Nariño', 'departament_Id' => 28],
            ['name' => 'Puerto Santander', 'departament_Id' => 28],
            ['name' => 'Tarapacá', 'departament_Id' => 28],
            ['name' => 'Inírida', 'departament_Id' => 29],
            ['name' => 'Barrancominas', 'departament_Id' => 29],
            ['name' => 'San Felipe', 'departament_Id' => 29],
            ['name' => 'Puerto Colombia', 'departament_Id' => 29],
            ['name' => 'La Guadalupe', 'departament_Id' => 29],
            ['name' => 'Cacahual', 'departament_Id' => 29],
            ['name' => 'Pana Pana', 'departament_Id' => 29],
            ['name' => 'Morichal', 'departament_Id' => 29],
            ['name' => 'Mapiripana', 'departament_Id' => 29],
            ['name' => 'San José Del Guaviare', 'departament_Id' => 30],
            ['name' => 'Calamar', 'departament_Id' => 30],
            ['name' => 'El Retorno', 'departament_Id' => 30],
            ['name' => 'Miraflores', 'departament_Id' => 30],
            ['name' => 'Mitú', 'departament_Id' => 31],
            ['name' => 'Carurú', 'departament_Id' => 31],
            ['name' => 'Pacoa', 'departament_Id' => 31],
            ['name' => 'Taraira', 'departament_Id' => 31],
            ['name' => 'Papunahua', 'departament_Id' => 31],
            ['name' => 'Yavaraté', 'departament_Id' => 31],
            ['name' => 'Puerto Carreño', 'departament_Id' => 32],
            ['name' => 'La Primavera', 'departament_Id' => 32],
            ['name' => 'Santa Rosalía', 'departament_Id' => 32],
            ['name' => 'Cumaribo', 'departament_Id' => 32],
        ];
    }

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        foreach ($this->municipalitys as $municipality) {

            Municipality::create([
                'department_id' => $municipality["departament_Id"],
                'name' => $municipality["name"],
            ]);
        }
    }
}
